CREATE DATABASE indigo_airline_analysis;

USE indigo_airline_analysis;

SELECT COUNT(*)
FROM profitability;

#1. What is the total revenue generated by IndiGo routes?
SELECT
ROUND(
SUM(revenue)/1000000000,
2
) AS Revenue_Billion
FROM profitability;

#2. What is the total profit generated?
SELECT
ROUND(
SUM(profit)/1000000000,
2
) AS Profit_Billion
FROM profitability;

#3. What is the overall company profit margin?
SELECT
ROUND(
(SUM(profit)/SUM(revenue))*100,
2
) AS Company_Margin
FROM profitability;

#4. Which are the top 10 most profitable routes?
SELECT
route,
ROUND(profit/1000000,2) AS Profit_Million
FROM profitability
ORDER BY profit DESC
LIMIT 10;

#5. Which are the bottom 10 least profitable routes?
SELECT
route,
ROUND(profit/1000000,2) AS Profit_Million
FROM profitability
ORDER BY profit ASC
LIMIT 10;

#6. Which airports generate the highest profit?
SELECT
source_airport_name,
ROUND(
SUM(profit)/1000000000,
2
) AS Profit_Billion
FROM profitability
GROUP BY source_airport_name
ORDER BY Profit_Billion DESC
LIMIT 10;

#7. Which airports operate the most routes?
SELECT
source_airport_name,
COUNT(*) AS Route_Count
FROM profitability
GROUP BY source_airport_name
ORDER BY Route_Count DESC
LIMIT 10;

#8. What is the average load factor across all routes?
SELECT
ROUND(
AVG(load_factor)*100,
2
) AS Avg_Load_Factor
FROM profitability;

#9. Which routes have load factor above 90%?
SELECT
route,
ROUND(
load_factor*100,
2
) AS Load_Factor
FROM profitability
WHERE load_factor > 0.90
ORDER BY load_factor DESC;

#10. Compare domestic and international route profitability
SELECT
route_type,
COUNT(*) AS Total_Routes,
ROUND(
SUM(revenue)/1000000000,
2
) AS Revenue_Billion,
ROUND(
SUM(profit)/1000000000,
2
) AS Profit_Billion
FROM profitability
GROUP BY route_type;

#11. Which routes have profit margin above 30%?
SELECT
route,
ROUND(
profit_margin,
2
) AS Margin
FROM profitability
WHERE profit_margin > 30
ORDER BY margin DESC;

#12. Which routes have negative profit?
SELECT
route,
ROUND(
profit/1000000,
2
) AS Loss_Million
FROM profitability
WHERE profit < 0
ORDER BY profit;

#13. What are the top 5 revenue-generating routes?
SELECT
route,
ROUND(
revenue/1000000,
2
) AS Revenue_Million
FROM profitability
ORDER BY revenue DESC
LIMIT 5;

#14. What is the average ticket price by route type?
SELECT
route_type,
ROUND(
AVG(avg_ticket_price),
2
) AS Avg_Ticket_Price
FROM profitability
GROUP BY route_type;

#15. Which airports have the highest passenger volume?
SELECT
source_airport_name,
SUM(passengers) AS Total_Passengers
FROM profitability
GROUP BY source_airport_name
ORDER BY Total_Passengers DESC
LIMIT 10;

#16. Which are the top 5 most profitable routes within each route category (Domestic vs International)?
WITH route_rank AS
(
    SELECT
        route,
        route_type,
        profit,

        RANK() OVER(
            PARTITION BY route_type
            ORDER BY profit DESC
        ) AS profit_rank

    FROM profitability
)
SELECT *
FROM route_rank
WHERE profit_rank <= 5;

#17. Which routes belong to the top 10% profitability segment?
WITH profit_percentile AS
(
    SELECT
        route,
        profit,
        NTILE(10) OVER(
            ORDER BY profit DESC
        ) AS percentile_group
    FROM profitability
)
SELECT *
FROM profit_percentile
WHERE percentile_group = 1;

#18. Which airports generate above-average profit and should be prioritized for network expansion?
WITH airport_profit AS
(
    SELECT
        source_airport_name,
        SUM(profit) AS total_profit
    FROM profitability
    GROUP BY source_airport_name
)
SELECT *
FROM airport_profit
WHERE total_profit >
(
    SELECT AVG(total_profit)
    FROM airport_profit
)
ORDER BY total_profit DESC;

#19. What percentage of IndiGo's total profit is contributed by each airport?
SELECT
    source_airport_name,
ROUND(
        SUM(profit) /
        (SELECT SUM(profit) FROM profitability)
        * 100,
        2
    ) AS Profit_Contribution_Percent
	FROM profitability
GROUP BY source_airport_name
ORDER BY Profit_Contribution_Percent DESC;

#20. Which routes generate high revenue but deliver poor profitability?
WITH route_stats AS
(
    SELECT
        route,
        revenue,
        profit,
        profit_margin
    FROM profitability
)
SELECT *
FROM route_stats
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM profitability
)
AND profit_margin < 10
ORDER BY revenue DESC;